/**
 * Local image registry for the marketing site.
 * All paths are served from /public — no runtime remote fetches.
 */
export const photos = {
  sky: "/images/hero/sky.jpg",
  house: "/images/hero/house.png",
  cloud: "/images/hero/cloud.png",
  fog: "/images/hero/smoke.png",
  skyline: "/images/hero/cta-skyline.jpg",
  why: "/images/services/interior.jpg",
  chevron1: "/images/arrows/chevron-1.jpg",
  chevron2: "/images/arrows/chevron-2.jpg",
  chevron3: "/images/arrows/chevron-3.jpg",
  chevron4: "/images/arrows/chevron-4.jpg",
  agentSmall: "/images/agents/portrait-small.jpg",
  agentLarge: "/images/agents/portrait-large.jpg",
  testimonial: "/images/agents/testimonial-preview.jpg",
  buy: "/images/services/buy.jpg",
  sell: "/images/services/sell.jpg",
  rent: "/images/services/rent.jpg",
  mortgage: "/images/services/mortgage.jpg",
  management: "/images/services/property-management.jpg",
  development: "/images/services/development.jpg",
  listing01: "/images/properties/listing-01.jpg",
  listing02: "/images/properties/listing-02.jpg",
  listing03: "/images/properties/listing-03.jpg",
  listing04: "/images/properties/listing-04.jpg",
  listing05: "/images/properties/listing-05.jpg",
  listing06: "/images/properties/listing-06.jpg",
  listing07: "/images/properties/listing-07.jpg",
  listing08: "/images/properties/listing-08.jpg",
  listing09: "/images/properties/listing-09.jpg",
  listing01b: "/images/properties/listing-10.jpg",
  listing01c: "/images/properties/listing-11.jpg",
  blog1: "/images/blog/harry-styles-neighborhood.png",
  blog2: "/images/blog/nyc-market-report.png",
  blog3: "/images/blog/philly-market.png",
  portrait1: "/images/agents/portrait-small.jpg",
  portrait2: "/images/agents/portrait-large.jpg",
  portrait3: "/images/agents/portrait-03.jpg",
  portrait4: "/images/agents/portrait-04.jpg",
  join: "/images/services/office.jpg",
  about: "/images/services/architecture.jpg",
};

export default photos;
