import { photos } from "./photos";

/**
 * محتوای محصول برای بازار املاک ایران.
 * این فایل ترجمهٔ سایت آمریکایی نیست — از نو برای کاربر ایرانی نوشته شده.
 * برند FIND، تصاویر و ساختار بصری حفظ می‌شوند؛ داده و اصطلاحات بومی‌اند.
 */
export const siteConfig = {
  locale: {
    lang: "fa",
    dir: "rtl",
  },

  brand: {
    name: "FIND",
    legalName: "FIND",
    tagline: "ملک درست را پیدا کنید",
  },

  metadata: {
    title: "FIND | جستجو، خرید و اجاره ملک در تهران",
    description:
      "پلتفرم معرفی فایل‌های منتخب مسکونی در شمال تهران. خرید، اجاره و همراهی مشاور متخصص تا نهایی شدن معامله.",
  },

  pageTitles: {
    search: "جستجوی ملک",
    agents: "مشاوران املاک",
    about: "درباره FIND",
    services: "خدمات",
    blog: "مجله املاک",
    contact: "تماس با ما",
    join: "همکاری با FIND",
  },

  contact: {
    officeLabel: "دفتر تهران",
    addressLine1: "تهران، ولیعصر، بالاتر از پارک‌وی",
    addressLine2: "برج نور، طبقه ۱۲",
    emailLabel: "ایمیل",
    email: "hello@find.ir",
    phoneLabel: "تلفن",
    phone: "۰۲۱-۹۱۰۹۱۰۹۰",
    phoneHref: "tel:+982191091090",
    emailHref: "mailto:hello@find.ir",
  },

  navigation: [
    { label: "جستجوی ملک", href: "/search" },
    { label: "مشاوران", href: "/agents" },
    { label: "همکاری", href: "/join" },
    {
      label: "خدمات",
      href: "/services",
      children: [
        { label: "کارشناسی و ارزیابی", href: "/services#mortgage" },
        { label: "مدیریت ملک", href: "/services#management" },
        { label: "مشاوره سرمایه‌گذاری", href: "/services#development" },
      ],
    },
    {
      label: "مجله",
      href: "/blog",
      children: [
        { label: "راهنماهای خرید", href: "/blog" },
        { label: "بازار و تحلیل", href: "/blog" },
      ],
    },
    { label: "درباره ما", href: "/about" },
  ],

  header: {
    signInLabel: "ورود",
    signInHref: "/contact",
    navAriaLabel: "منوی اصلی",
    menuAriaLabel: "منو",
  },

  hero: {
    heading: "ملک درست را پیدا کنید",
    lead: "فایل‌های منتخب شمال تهران.",
    leadEmphasis: "با مشاوری که محله را می‌شناسد.",
    ctaLabel: "جستجوی ملک",
    ctaHref: "/search",
    images: {
      sky: photos.sky,
      house: photos.house,
      cloud: photos.cloud,
      smoke: photos.fog,
    },
  },

  why: {
    id: "why",
    heading: "چرا FIND",
    body: "خرید یا اجاره ملک در تهران فقط دیدن عکس نیست.",
    bodyEmphasis:
      "ما فایل را با نیاز واقعی‌تان می‌سنجیم؛ نور، دسترسی، سند و قیمت را شفاف می‌کنیم تا با اطمینان تصمیم بگیرید.",
    image: photos.why,
    videoSrc: "/videos/why-us.mp4",
  },

  identity: {
    heading: "ملک فقط دیوار و سقف نیست.",
    headingEmphasis: "سبک زندگی است.",
    body: "محله، دسترسی به مدرسه و مترو، آرامش کوچه و کیفیت ساخت مهم‌تر از شعارهای لوکس‌اند.",
    bodyEmphasis: "FIND کمک می‌کند همان چیزی را پیدا کنید که واقعاً به زندگی‌تان می‌خورد.",
    chevrons: [photos.chevron1, photos.chevron2, photos.chevron3, photos.chevron4],
  },

  process: {
    heading: "مسیر معامله،",
    headingEmphasis: "ساده و شفاف.",
    ctaLabel: "شروع جستجو",
    ctaHref: "/search",
    stepsLabel: "مراحل کار:",
    steps: [
      {
        title: "نیازتان را دقیق می‌کنیم.",
        text: "بودجه، محله، متراژ و اولویت‌های زندگی را با هم مشخص می‌کنیم.",
      },
      {
        title: "فایل مناسب معرفی می‌شود.",
        text: "فقط فایل‌هایی که با معیارهای شما هم‌خوانی دارند روی میز می‌آیند.",
      },
      {
        title: "تا قرارداد کنارتان هستیم.",
        text: "بازدید، مذاکره و هماهنگی‌های نهایی را با مشاور پیش می‌برید.",
      },
    ],
  },

  agents: {
    id: "join",
    label: "برای مشاوران",
    heading: "فایل خوب،",
    headingEmphasis: "اعتماد می‌سازد.",
    body: "در FIND مشاور فقط واسطه نیست؛ همراه معامله است.",
    bodyEmphasis:
      "ابزار معرفی فایل، پشتیبانی تیم و مسیر رشد شفاف در اختیار مشاورانی است که می‌خواهند در بازار شمال تهران حرفه‌ای کار کنند.",
    ctaLabel: "درخواست همکاری",
    ctaHref: "/join",
    portraitSmall: photos.agentSmall,
    portraitLarge: photos.agentLarge,
    directoryHeading: "تیم مشاوران",
    directoryEmphasis: "FIND",
    directoryBody:
      "مشاورانی مسلط به محله‌های شمال تهران که از اولین تماس تا قرارداد کنارتان می‌مانند.",
    people: [
      {
        id: "arash",
        name: "آرش نادری",
        title: "مشاور ارشد فروش",
        neighborhood: "فرمانیه، الهیه، فرشته",
        email: "arash@find.ir",
        phone: "۰۹۱۲-۰۰۰-۱۱۰۱",
        image: photos.portrait1,
        bio: "تمرکز روی واحدهای نوساز و بازسازی‌شده در فرمانیه و الهیه. در بازدید، نور و پلان را دقیق بررسی می‌کند.",
      },
      {
        id: "sara",
        name: "سارا مرادی",
        title: "مشاور خرید و سرمایه‌گذاری",
        neighborhood: "زعفرانیه، نیاوران، کامرانیه",
        email: "sara@find.ir",
        phone: "۰۹۱۲-۰۰۰-۱۱۰۲",
        image: photos.portrait2,
        bio: "کمک می‌کند بین سکونت و سرمایه‌گذاری تعادل برقرار شود؛ مخصوصاً برای خانواده‌هایی که اولین خرید جدی‌شان را انجام می‌دهند.",
      },
      {
        id: "amir",
        name: "امیرحسین کاظمی",
        title: "مشاور اجاره و رهن",
        neighborhood: "سعادت‌آباد، شهرک غرب، جردن",
        email: "amir@find.ir",
        phone: "۰۹۱۲-۰۰۰-۱۱۰۳",
        image: photos.portrait3,
        bio: "فایل‌های رهن و اجاره را با بودجه واقعی تنظیم می‌کند و قبل از بازدید، شرایط مالک و قرارداد را شفاف می‌گوید.",
      },
      {
        id: "negar",
        name: "نگار احمدی",
        title: "مشاور فروش شمال تهران",
        neighborhood: "قیطریه، دروس، پاسداران",
        email: "negar@find.ir",
        phone: "۰۹۱۲-۰۰۰-۱۱۰۴",
        image: photos.portrait4,
        bio: "با محله‌های آرام‌تر شمال تهران کار می‌کند و روی سند، پارکینگ و دسترسی روزمره حساس است.",
      },
    ],
  },

  testimonials: {
    heading: "تجربه کسانی که",
    headingEmphasis: "با FIND معامله کردند.",
    previewImage: photos.testimonial,
    items: [
      {
        quote:
          "دنبال واحدی در فرمانیه بودیم که هم نور خوب داشته باشد هم برای بچه مدرسه نزدیک باشد. مشاور بدون عجله چند فایل واقعی آورد و تا قرارداد همراه ماند.",
        author: "مریم و رضا",
      },
      {
        quote:
          "برای اجاره در سعادت‌آباد بودجه مشخصی داشتیم. فایل‌هایی که معرفی شد دقیقاً در همان بازه بود و شرایط رهن قبل از بازدید روشن شد.",
        author: "کیانوش م.",
      },
      {
        quote:
          "اولین خرید جدی‌مان بود. توضیح سند و هزینه‌های جانبی شفاف بود؛ حس نکردیم فقط می‌خواهند معامله را ببندند.",
        author: "الهام ن.",
      },
      {
        quote:
          "واحد زعفرانیه را دو بار بازدید کردیم و ایرادهای پلان را همانجا گفتند. همین صداقت باعث شد با اطمینان پیش برویم.",
        author: "بهرام ک.",
      },
      {
        quote:
          "برای سرمایه‌گذاری بین نیاوران و کامرانیه مردد بودیم. مقایسه قیمت و نقدشوندگی محله کمک کرد تصمیم بگیریم.",
        author: "سارا و امین",
      },
    ],
  },

  features: {
    id: "services",
    caption: "خدمات",
    heading: "FIND در مسیر",
    headingEmphasis: "معامله کنارتان است",
    brief: "از جستجوی فایل تا هماهنگی بازدید و جمع‌بندی نهایی،",
    briefEmphasis: "یک مسیر مشخص و قابل پیگیری دارید.",
    ctaLabel: "شروع گفتگو",
    ctaHref: "/contact",
    items: [
      {
        id: "buy",
        title: "خرید",
        description:
          "فایل‌های فروش را بر اساس بودجه، محله و اولویت زندگی‌تان فیلتر می‌کنیم. قبل از بازدید، وضعیت سند و امکانات واحد را مرور می‌کنید.",
        image: photos.buy,
        href: "/search",
      },
      {
        id: "sell",
        title: "فروش",
        description:
          "برای فروش ملک، قیمت‌گذاری واقع‌بینانه، آماده‌سازی فایل و معرفی به خریداران جدی را با مشاور پیش می‌برید.",
        image: photos.sell,
        href: "/contact",
      },
      {
        id: "rent",
        title: "اجاره",
        description:
          "رهن و اجاره را شفاف می‌چینیم؛ از بودجه ماهانه تا شرایط مالک و زمان تخلیه، قبل از بازدید مشخص می‌شود.",
        image: photos.rent,
        href: "/search",
      },
    ],
  },

  support: {
    id: "support",
    heading: "همراهی",
    headingMiddle: "بعد از",
    headingBuy: "جستجو",
    headingAnd: "و بازدید",
    body: "معامله با دیدن فایل تمام نمی‌شود.",
    bodyEmphasis:
      "کارشناسی، ارزیابی و هماهنگی‌های اجرایی را هم در صورت نیاز کنار مسیر خرید یا اجاره قرار می‌دهیم.",
    ctaLabel: "مشاهده خدمات",
    ctaHref: "/services",
    items: [
      {
        id: "mortgage",
        title: "کارشناسی و ارزیابی ملک",
        text: "بررسی وضعیت واحد، قیمت پیشنهادی و نکات فنی قبل از تصمیم نهایی.",
        image: photos.mortgage,
        ctaLabel: "درخواست کارشناسی",
        href: "/contact",
      },
      {
        id: "management",
        title: "مدیریت و نگهداری ملک",
        text: "هماهنگی امور جاری ملک برای مالکانی که فرصت پیگیری روزانه ندارند.",
        image: photos.management,
        ctaLabel: "اطلاعات بیشتر",
        href: "/contact",
      },
      {
        id: "development",
        title: "مشاوره سرمایه‌گذاری",
        text: "مقایسه محله، نقدشوندگی و بازده احتمالی برای خرید هوشمندتر.",
        image: photos.development,
        ctaLabel: "مشاوره بگیریم",
        href: "/contact",
      },
    ],
  },

  properties: {
    id: "properties",
    caption: "فایل‌ها",
    heading: "ملک‌های",
    headingEmphasis: "منتخب",
    body: "فایل‌هایی از شمال تهران؛ با تمرکز روی نور، دسترسی، سند و قیمت منطقی.",
    viewAllLabel: "همه فایل‌ها",
    viewAllHref: "/search",
    bedsLabel: "خواب",
    bathsLabel: "حمام",
    areaLabel: "مترمربع",
    inquireLabel: "درخواست بازدید",
    similarLabel: "فایل‌های مشابه",
    items: [
      {
        id: "listing-01",
        title: "آپارتمان ۱۹۰ متری در فرمانیه",
        neighborhood: "فرمانیه",
        address: "تهران، فرمانیه، کوچه نسترن",
        price: "۸۵ میلیارد تومان",
        priceValue: 85000000000,
        beds: 3,
        baths: 2,
        area: 190,
        type: "آپارتمان",
        status: "برای فروش",
        year: 1401,
        floor: "۵ از ۸",
        parking: 2,
        agentId: "arash",
        image: photos.listing01,
        gallery: [photos.listing01, photos.listing01b, photos.listing01c],
        href: "/properties/listing-01",
        featured: true,
        description:
          "واحد ۱۹۰ متری در یکی از کوچه‌های آرام فرمانیه با نورگیری جنوبی، آشپزخانه اوپن و تراس قابل استفاده. پارکینگ مسقف و انباری دارد و سند تک‌برگ است.",
        amenities: ["پارکینگ مسقف", "آسانسور", "انباری", "تراس", "سند تک‌برگ"],
      },
      {
        id: "listing-02",
        title: "پنت‌هاوس ۲۴۰ متری در الهیه",
        neighborhood: "الهیه",
        address: "تهران، الهیه، خیابان فرشته",
        price: "۱۴۵ میلیارد تومان",
        priceValue: 145000000000,
        beds: 4,
        baths: 3,
        area: 240,
        type: "پنت‌هاوس",
        status: "برای فروش",
        year: 1402,
        floor: "آخر",
        parking: 3,
        agentId: "sara",
        image: photos.listing02,
        gallery: [photos.listing02, photos.listing01b, photos.listing04],
        href: "/properties/listing-02",
        featured: true,
        description:
          "پنت‌هاوس نوساز با سقف بلند، فضای نشیمن یکپارچه و چشم‌انداز باز. مناسب سکونت خانوادگی یا اقامت کم‌جمعیت با استاندارد بالا.",
        amenities: ["لابی", "نگهبانی", "استخر", "پارکینگ مهمان", "سالن اجتماعات"],
      },
      {
        id: "listing-03",
        title: "آپارتمان ۱۶۵ متری در زعفرانیه",
        neighborhood: "زعفرانیه",
        address: "تهران، زعفرانیه، خیابان مقدس اردبیلی",
        price: "۹۸ میلیارد تومان",
        priceValue: 98000000000,
        beds: 3,
        baths: 2,
        area: 165,
        type: "آپارتمان",
        status: "برای فروش",
        year: 1398,
        floor: "۳ از ۶",
        parking: 2,
        agentId: "sara",
        image: photos.listing03,
        gallery: [photos.listing03, photos.listing05, photos.listing01c],
        href: "/properties/listing-03",
        featured: true,
        description:
          "واحد بازسازی‌شده با متریال به‌روز، خواب مستر و آشپزخانه تجهیزشده. دسترسی به تجریش و مراکز خدماتی سریع است.",
        amenities: ["بازسازی‌شده", "خواب مستر", "انباری", "آسانسور", "پارکینگ"],
      },
      {
        id: "listing-04",
        title: "آپارتمان ۲۲۰ متری در نیاوران",
        neighborhood: "نیاوران",
        address: "تهران، نیاوران، خیابان مژده",
        price: "۱۲۰ میلیارد تومان",
        priceValue: 120000000000,
        beds: 4,
        baths: 3,
        area: 220,
        type: "آپارتمان",
        status: "برای فروش",
        year: 1400,
        floor: "۴ از ۷",
        parking: 2,
        agentId: "negar",
        image: photos.listing04,
        gallery: [photos.listing04, photos.listing02, photos.listing08],
        href: "/properties/listing-04",
        featured: true,
        description:
          "واحدی با پلان کاربردی، اتاق کار جدا و بالکن غرب‌گیر. محله آرام است و برای خانواده با فرزند مناسب به‌نظر می‌رسد.",
        amenities: ["بالکن", "اتاق کار", "پارکینگ", "آسانسور", "نگهبانی"],
      },
      {
        id: "listing-05",
        title: "آپارتمان ۱۳۵ متری در سعادت‌آباد",
        neighborhood: "سعادت‌آباد",
        address: "تهران، سعادت‌آباد، میدان کاج",
        price: "رهن ۲٫۸ میلیارد · اجاره ۵۵ میلیون",
        priceValue: 2800000000,
        beds: 2,
        baths: 2,
        area: 135,
        type: "آپارتمان",
        status: "برای اجاره",
        year: 1399,
        floor: "۶ از ۱۰",
        parking: 1,
        agentId: "amir",
        image: photos.listing05,
        gallery: [photos.listing05, photos.listing07, photos.listing01b],
        href: "/properties/listing-05",
        featured: true,
        description:
          "واحد روشن و مرتب نزدیک میدان کاج؛ مناسب زوج یا خانواده کوچک. رهن و اجاره قابل تبدیل جزئی است و تخلیه از اول ماه بعد.",
        amenities: ["پارکینگ", "آسانسور", "انباری", "بالکن", "غیرمبله"],
      },
      {
        id: "listing-06",
        title: "آپارتمان ۱۷۵ متری در ولنجک",
        neighborhood: "ولنجک",
        address: "تهران، ولنجک، خیابان یمن",
        price: "۷۲ میلیارد تومان",
        priceValue: 72000000000,
        beds: 3,
        baths: 2,
        area: 175,
        type: "آپارتمان",
        status: "برای فروش",
        year: 1396,
        floor: "۲ از ۵",
        parking: 2,
        agentId: "arash",
        image: photos.listing06,
        gallery: [photos.listing06, photos.listing08, photos.listing03],
        href: "/properties/listing-06",
        featured: true,
        description:
          "واحد جنوبی با سقف نسبتاً بلند و آشپزخانه کاربردی. دسترسی به اتوبان و مراکز خرید خوب است؛ برای سکونت روزمره مناسب.",
        amenities: ["نور جنوبی", "پارکینگ", "انباری", "آسانسور", "سند تک‌برگ"],
      },
      {
        id: "listing-07",
        title: "آپارتمان ۱۱۰ متری در شهرک غرب",
        neighborhood: "شهرک غرب",
        address: "تهران، شهرک غرب، فاز ۲",
        price: "رهن ۱٫۹ میلیارد · اجاره ۴۰ میلیون",
        priceValue: 1900000000,
        beds: 2,
        baths: 1,
        area: 110,
        type: "آپارتمان",
        status: "برای اجاره",
        year: 1395,
        floor: "۳ از ۶",
        parking: 1,
        agentId: "amir",
        image: photos.listing07,
        gallery: [photos.listing07, photos.listing05, photos.listing09],
        href: "/properties/listing-07",
        featured: false,
        description:
          "واحد جمع‌وجور و تمیز در فاز ۲؛ نزدیک خدمات روزمره. برای شروع زندگی مشترک یا اسکان کاری گزینه منطقی است.",
        amenities: ["پارکینگ", "آسانسور", "انباری", "غیرمبله"],
      },
      {
        id: "listing-08",
        title: "خانه ویلایی ۲۸۰ متری در مهرشهر",
        neighborhood: "مهرشهر",
        address: "کرج، مهرشهر، فاز ۳",
        price: "۴۸ میلیارد تومان",
        priceValue: 48000000000,
        beds: 4,
        baths: 3,
        area: 280,
        type: "خانه ویلایی",
        status: "برای فروش",
        year: 1397,
        floor: "دوبلکس",
        parking: 2,
        agentId: "negar",
        image: photos.listing08,
        gallery: [photos.listing08, photos.listing06, photos.listing02],
        href: "/properties/listing-08",
        featured: false,
        description:
          "ویلای دوبلکس با حیاط قابل استفاده و پارکینگ مستقل. فضای داخلی روشن است و برای خانواده پرتعداد مناسب به‌نظر می‌رسد.",
        amenities: ["حیاط", "پارکینگ مستقل", "انباری", "آشپزخانه مجهز", "سند"],
      },
      {
        id: "listing-09",
        title: "آپارتمان ۱۵۰ متری در قیطریه",
        neighborhood: "قیطریه",
        address: "تهران، قیطریه، خیابان شریفی",
        price: "۶۵ میلیارد تومان",
        priceValue: 65000000000,
        beds: 3,
        baths: 2,
        area: 150,
        type: "آپارتمان",
        status: "برای فروش",
        year: 1400,
        floor: "۷ از ۹",
        parking: 1,
        agentId: "negar",
        image: photos.listing09,
        gallery: [photos.listing09, photos.listing01, photos.listing07],
        href: "/properties/listing-09",
        featured: false,
        description:
          "واحد مرتفع با دید نسبتاً باز و پلان بدون راهروی اضافه. نزدیکی به پارک قیطریه از نقاط قوت فایل است.",
        amenities: ["دید باز", "پارکینگ", "آسانسور", "انباری", "لابی"],
      },
    ],
  },

  journal: {
    id: "journal",
    heading: "مجله",
    headingAmp: "و",
    headingResources: "راهنما",
    body: "نکته‌های کاربردی برای خرید، اجاره و بررسی فایل در تهران؛ کوتاه و قابل استفاده.",
    ctaLabel: "مشاهده مجله",
    ctaHref: "/blog",
    readMoreLabel: "ادامه مطلب",
    posts: [
      {
        slug: "buy-apartment-north-tehran",
        date: "۱۴۰۴/۰۶/۱۲",
        title: "راهنمای خرید آپارتمان در شمال تهران",
        excerpt:
          "قبل از بازدید در فرمانیه، زعفرانیه یا نیاوران، بودجه، سند و اولویت‌های زندگی را چطور مشخص کنید.",
        image: photos.blog1,
        href: "/blog/buy-apartment-north-tehran",
        paragraphs: [
          "خرید در شمال تهران معمولاً با محدودیت بودجه و تنوع فایل روبه‌روست. اول مشخص کنید اولویت‌تان سکونت است یا حفظ ارزش سرمایه؛ بعد محله را کوتاه کنید.",
          "در بازدید به نورگیری، صدای کوچه، پارکینگ مهمان و وضعیت مشاعات دقیق شوید. قیمت پیشنهادی را با چند فایل مشابه همان محدوده مقایسه کنید، نه با کل شهر.",
        ],
      },
      {
        slug: "documents-before-purchase",
        date: "۱۴۰۴/۰۳/۲۴",
        title: "قبل از خرید ملک چه مدارکی را بررسی کنیم؟",
        excerpt:
          "سند، پایان‌کار، صورت‌مجلس تفکیکی و بدهی‌های ساختمان؛ چک‌لیست کوتاه قبل از پرداخت بیعانه.",
        image: photos.blog2,
        href: "/blog/documents-before-purchase",
        paragraphs: [
          "بدون بررسی مدارک، هیچ فایلی را نهایی نکنید. تک‌برگ بودن سند، وضعیت بازداشت و مطابقت متراژ با پایان‌کار از اولین سوال‌هاست.",
          "اگر واحد در ساختمان نوساز است، وضعیت صورت‌مجلس و تعهدات سازنده را شفاف بخواهید. مشاور خوب این موارد را قبل از بازدید جدی مطرح می‌کند.",
        ],
      },
      {
        slug: "rahn-vs-rent",
        date: "۱۴۰۴/۰۱/۱۵",
        title: "تفاوت رهن و اجاره؛ کدام ترکیب به‌صرفه‌تر است؟",
        excerpt:
          "با بودجه ثابت، چه زمانی رهن کامل بهتر است و چه زمانی ترکیب رهن و اجاره ماهانه منطقی‌تر می‌شود.",
        image: photos.blog3,
        href: "/blog/rahn-vs-rent",
        paragraphs: [
          "اگر نقدینگی بالایی دارید و نمی‌خواهید هر ماه پرداخت ثابت داشته باشید، رهن کامل معمولاً آرامش بیشتری می‌دهد. اما قدرت خریدتان را هم قفل می‌کند.",
          "ترکیب رهن کمتر و اجاره ماهانه برای کسانی که نقدینگی را جای دیگری نیاز دارند رایج‌تر است. مهم این است که سقف اجاره را با درآمد ماهانه‌تان واقعی ببندید.",
        ],
      },
    ],
  },

  cta: {
    id: "contact",
    heading: "برای شروع،",
    headingEmphasis: "یک گفتگوی کوتاه کافی است.",
    ctaLabel: "درخواست مشاوره",
    ctaHref: "/contact",
    background: photos.skyline,
  },

  aboutPage: {
    heading: "FIND برای",
    headingEmphasis: "معامله شفاف ساخته شده.",
    body: "ما فایل‌های منتخب مسکونی را در تهران معرفی می‌کنیم و مسیر خرید یا اجاره را با مشاور متخصص ساده نگه می‌داریم؛ بدون وعده اضافه.",
    stats: [
      { value: "۱۲۰۰+", label: "فایل بررسی‌شده" },
      { value: "۴۰+", label: "مشاور فعال" },
      { value: "تهران", label: "تمرکز اصلی بازار" },
    ],
  },

  joinPage: {
    heading: "اگر مشاورید،",
    headingEmphasis: "اینجا جا دارید.",
    body: "برای مشاورانی که می‌خواهند فایل جدی معرفی کنند و مسیر رشد شفافی داشته باشند، همکاری با FIND یک گزینه واقعی است.",
    ctaLabel: "ارسال درخواست",
  },

  contactPage: {
    heading: "بگویید دنبال",
    headingEmphasis: "چه ملکی هستید.",
    body: "محله، بودجه و زمان‌بندی‌تان را بنویسید. تیم FIND فایل‌های نزدیک به نیازتان را پیگیری می‌کند.",
    successTitle: "پیامتان ثبت شد.",
    successBody: "به‌زودی یکی از مشاوران تماس می‌گیرد. اگر فوری است، با دفتر تهران تماس بگیرید.",
  },

  notFound: {
    heading: "این صفحه پیدا نشد.",
    body: "ممکن است لینک قدیمی باشد یا فایل از دسترس خارج شده باشد.",
    backLabel: "بازگشت به",
  },

  footer: {
    newsletterTitle: "عضویت در خبرنامه فایل‌ها",
    newsletterPlaceholder: "ایمیل شما",
    newsletterSubmit: "عضویت",
    nav: [
      { label: "جستجوی ملک", href: "/search" },
      { label: "مشاوران", href: "/agents" },
      { label: "همکاری", href: "/join" },
      { label: "درباره ما", href: "/about" },
      { label: "تماس", href: "/contact" },
    ],
    social: [
      { label: "اینستاگرام", href: "https://instagram.com" },
      { label: "لینکدین", href: "https://linkedin.com" },
      { label: "تلگرام", href: "https://t.me" },
      { label: "آپارات", href: "https://aparat.com" },
    ],
    legal: [
      { label: "شرایط استفاده", href: "/about" },
      { label: "حریم خصوصی", href: "/about" },
      { label: "راهنمای معامله", href: "/blog" },
      { label: "تماس با پشتیبانی", href: "/contact" },
    ],
    vouchers: [
      "اطلاعات فایل‌ها جنبه معرفی دارند و قبل از معامله باید بررسی شوند.",
      "FIND واسطه معرفی مشاور و فایل است؛ تصمیم نهایی با شماست.",
    ],
    copyrightPrefix: "کپی‌رایت ©",
    copyrightYear: "۱۴۰۴",
  },

  searchPage: {
    heading: "جستجوی",
    headingEmphasis: "ملک",
    subheading: "محله، بودجه و تعداد خواب را تنظیم کنید تا فایل‌های نزدیک به نیازتان را ببینید.",
    filtersLabel: "فیلتر فایل",
    neighborhoodsLabel: "موقعیت",
    allNeighborhoodsLabel: "همه",
    statusLabel: "نوع معامله",
    forSaleLabel: "خرید",
    forRentLabel: "اجاره",
    forSaleValue: "برای فروش",
    forRentValue: "برای اجاره",
    priceLabel: "بازه قیمت",
    anyPriceLabel: "همه قیمت‌ها",
    bedsBathsLabel: "تعداد خواب",
    anyBedsLabel: "همه",
    resultsSuffix: "فایل",
    sortLabel: "مرتب‌سازی:",
    sortNewest: "جدیدترین",
    sortPriceAsc: "ارزان‌تر",
    sortPriceDesc: "گران‌تر",
    emptyLabel: "با این فیلتر فایلی پیدا نشد. یک شرط را کمتر کنید و دوباره جستجو کنید.",
    clearLabel: "پاک کردن فیلترها",
    priceRanges: [
      { label: "همه قیمت‌ها", min: 0, max: Infinity },
      { label: "زیر ۲۰ میلیارد", min: 0, max: 20000000000 },
      { label: "۲۰ تا ۸۰ میلیارد", min: 20000000000, max: 80000000000 },
      { label: "بالای ۸۰ میلیارد", min: 80000000000, max: Infinity },
    ],
  },

  forms: {
    nameLabel: "نام و نام خانوادگی",
    namePlaceholder: "مثلاً سارا مرادی",
    emailLabel: "ایمیل",
    emailPlaceholder: "ایمیل خود را بنویسید",
    phoneLabel: "شماره موبایل",
    phonePlaceholder: "۰۹۱۲۰۰۰۰۰۰۰",
    messageLabel: "توضیح نیاز",
    messagePlaceholder: "محله، بودجه و نوع ملک را کوتاه بنویسید",
    sendLabel: "ارسال درخواست",
    sendingLabel: "در حال ارسال…",
  },
};

export default siteConfig;
